name: flutter_app
description: A new Flutter project
version: 1.0.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6  
  provider: ^6.0.3
  geolocator: ^11.0.0  
  intl: ^0.17.0  
  file_picker: ^5.5.0  
  sliding_up_panel: ^2.0.0
  shared_preferences: ^2.0.13
  flutter_map: ^3.1.0  
  latlong2: ^0.8.2
  google_maps_flutter: ^2.1.1
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/common/AppIcon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter:
  uses-material-design: true
  assets:
  - assets/common/
  - assets/user/
  - assets/driver/
