name: flutter_app
description: A new Flutter project
version: 1.0.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  provider: ^6.0.3
  google_maps_flutter: ^2.1.1
  geolocator: ^10.1.0
  intl: ^0.17.0
  file_picker: ^5.0.1
  sliding_up_panel: ^2.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  dio: ^5.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  open_street_map_search_and_pick: ^0.1.1
  
flutter:
  uses-material-design: true
  assets:
  - assets/common/
  - assets/user/
  - assets/driver/
